/* NOTE: AUTO-GENERATED by midc, DON'T edit!! */

CREATE TABLE IF NOT EXISTS `landlord3_state` (
	`uuid` TEXT   ,
	`playing` INT(10)   ,
	`leftover_wild_cards` TEXT   ,
	`first_landlord_pos` INT(4)   ,
	`stage` TEXT   ,
	`first_bider` INT(4)   ,
	`turn` INT(4)   ,
	`landlord` INT(4)   ,
	`doubled` TEXT   ,
	`last_pos` INT(4)   ,
	`last_hands` TEXT   ,
	`players` TEXT   ,
	PRIMARY KEY (`uuid`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

